In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.DataFrame({
    "color":["white","black"]
})

In [3]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()

In [8]:
encoded=encoder.fit_transform(df[["color"]]).toarray()

In [10]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [12]:
pd.concat([df,encoder_df],axis=1)

   color  color_black  color_white
0  white          0.0          1.0
1  black          1.0          0.0

In [16]:
encoder.transform([["white"]]).toarray()

c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 1.]])

In [17]:
from sklearn.preprocessing import OrdinalEncoder

In [23]:
df=pd.DataFrame(
    {
        "city":["baku","london","new york","baku"],
        "price":[200,100,300,130]
    }
)

In [24]:
df

       city  price
0      baku    200
1    london    100
2  new york    300
3      baku    130

In [26]:
mean_price=df.groupby("city")["price"].mean()

In [27]:
df["city_encoded"]=df["city"].map(mean_price)

In [28]:
df

       city  price  city_encoded
0      baku    200         165.0
1    london    100         100.0
2  new york    300         300.0
3      baku    130         165.0